### ISSUE TITLE
Panel wont connect to server despite following instructions on github

### ISSUE THREAD

**Issue by EnderSlime123** [Speentie8081/HardScene_Bukkit-RemoteTerminal#1]
I followed all the instructions via this GitHub, but upon putting the IP that cpanel gives me and logging in, the panel isn't connected to the server.

If this is a dead plugin, then get rid of the site and the plugin itself.

**Comment by Speentie8081** [comment]
This is not dead, please contact me on discord DEV ● Speentie8081#6124 and I can help you diagnose this issue.

**Comment by Speentie8081** [comment]
[Watch this video](https://www.youtube.com/watch?v=hB1AAu3lO44) I just finished recording it and it shows exactly how to get it working on your server. If it is still not working after doing this then your host is blocking outgoing connections on port 2083.

**Comment by Speentie8081** [comment]
I just finished setting up a [jenkins server](https://ci.skorrloregaming.com/job/HardScene_Bukkit-RemoteTerminal/) for downloading development builds of rTerminal cPanel without having to compile it manually, this may be helpful to you.
