### ISSUE TITLE
Unable to connect to wscon.rterminal.net:2083

### ISSUE THREAD

**Issue by RubizZ** [Speentie8081/HardScene_Bukkit-RemoteTerminal#3]
My host (for any reasons that I don't know) doesn't have this port opened, or I don't know why it doesn't connect to it. Can I change the port?

**Comment by Speentie8081** [comment]
The port is set by the proxy not by the plugin so it cannot be configured. Port 2083 is proxied through Cloudflare as well as our cpanel to maintain upmost security. I will need your error logs and your host name.

**Comment by RubizZ** [comment]
Here you have

**Comment by Speentie8081** [comment]
This does not show the name of your host, I need to know the name of your host.
Please use the latest version of the plugin from [our development builds repository](https://ci.devon.com.de/job/HardScene_Bukkit-RemoteTerminal/).
If it is still not working then your host is blocking outbound connections to our bypass proxy.
I have seen this behavior in some free server hosts, which I am not allowed to name.

**Comment by RubizZ** [comment]
Theminecrafthosting

Rubén

**Comment by Speentie8081** [comment]
If it is feasible, I do recommend you switch to Server.pro which is certified to work with our panel. They offer free servers and if you must they also have premium servers at a low price. I just spoke with a represenative for Theminecrafthosting and they say that they block all outbound connections.
